# 这是一个注释，用来简单描述这个工作流的用途
name: Test Project  # 定义工作流的名称，这个名称会在GitHub Actions页面中显示

# 定义触发器，指定什么情况下会执行这个工作流
on:
  pull_request:  # 当有Pull Request（拉取请求）时触发
    branches:  # 指定只有针对特定分支的PR时才触发
      - main  # 只有针对main分支的Pull Request时才会执行这个工作流

# 定义工作流中的任务（jobs）
jobs:
  test:  # 定义一个名为"test"的任务
    runs-on: ubuntu-latest  # 指定运行环境为最新版本的Ubuntu虚拟机
    container:  # 指定在容器中运行任务
      image: node:20  # 使用Node.js 20版本的Docker镜像作为运行环境
    steps:  # 定义任务中的具体步骤
      - uses: actions/checkout@v3  # 使用GitHub官方的checkout动作来拉取代码到运行环境
        with:  # 为checkout动作提供参数
          node-version: 20  # 指定Node.js版本为20（注意：这个参数在checkout动作中是无效的）
      - run: npm ci  # 执行npm ci命令，用于快速、可靠地安装依赖包（基于package-lock.json）
      - run: npm run test  # 执行npm run test命令，运行项目中定义的测试脚本
      - run: npm run build  # 执行npm run build命令，构建项目
      - run: echo "Hello, world!"  # 执行echo命令，输出"Hello, world!"到控制台


